# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InfoManage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleform',
            name='staff_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_form_username', to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
        migrations.AddField(
            model_name='produceform',
            name='assembly_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_form_ass_name', to='InfoManage.AssemblyLine', verbose_name='生产线'),
        ),
        migrations.AddField(
            model_name='produceform',
            name='hpro_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produce_form_hp_name', to='InfoManage.HalfProduct', verbose_name='半成品'),
        ),
        migrations.AddField(
            model_name='produceform',
            name='pro_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produce_form_pro_name', to='InfoManage.Product', verbose_name='成品'),
        ),
        migrations.AddField(
            model_name='outstorform',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_store_form_username', to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
        migrations.AddField(
            model_name='outstordetail',
            name='good_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_store_detail_good_name', to='InfoManage.StorDetail', verbose_name='货物名'),
        ),
        migrations.AddField(
            model_name='outstordetail',
            name='osf_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_store_detail_osf_name', to='InfoManage.OutStorForm', verbose_name='出库表'),
        ),
        migrations.AddField(
            model_name='orderformgoods',
            name='of_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_form_goods_of_name', to='InfoManage.OrderForm', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='orderformgoods',
            name='rm_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_form_goods_rm_name', to='InfoManage.RawMaterial', verbose_name='材料'),
        ),
        migrations.AddField(
            model_name='orderform',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_form_username', to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
        migrations.AddField(
            model_name='orderform',
            name='ven_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_form_ven_name', to='InfoManage.Vender', verbose_name='供货商'),
        ),
        migrations.AddField(
            model_name='meterial',
            name='hp_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meterial_hp_name', to='InfoManage.HalfProduct', verbose_name='半成品'),
        ),
        migrations.AddField(
            model_name='meterial',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meterial_good_name', to='InfoManage.StorDetail', verbose_name='材料'),
        ),
        migrations.AddField(
            model_name='meterial',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meterial_pro_name', to='InfoManage.Product', verbose_name='成品'),
        ),
    ]
