# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InfoManage', '0002_auto_20180509_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyline',
            name='leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AsseblyLine', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='meterial',
            name='hp_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meterial_hp_name', to='InfoManage.HalfProduct', verbose_name='半成品'),
        ),
        migrations.AlterField(
            model_name='meterial',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meterial_pro_name', to='InfoManage.Product', verbose_name='成品'),
        ),
    ]
