# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InfoManage', '0003_auto_20180511_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyline',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AsseblyLine', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='wasteform',
            name='pf_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='waste_product', to='InfoManage.ProduceForm', verbose_name='生产目标表'),
        ),
    ]
