# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InfoManage', '0004_auto_20180512_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleform',
            name='deliver_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='交货时间'),
        ),
        migrations.AlterField(
            model_name='saleform',
            name='out_stor_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出库时间'),
        ),
        migrations.AlterField(
            model_name='saleform',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='wasteform',
            name='pf_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_product', to='InfoManage.ProduceForm', verbose_name='生产目标表'),
        ),
    ]
