# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoManage', '0005_auto_20180513_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleformproduct',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='价格'),
        ),
    ]
