# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoManage', '0006_auto_20180513_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produceform',
            name='pf_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='表名'),
        ),
        migrations.AlterField(
            model_name='saleform',
            name='sf_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='表名'),
        ),
        migrations.AlterField(
            model_name='saleformproduct',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='价格'),
        ),
    ]
