# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfoManage', '0007_auto_20180513_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleformproduct',
            name='price',
        ),
    ]
