# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InfoManage', '0008_remove_saleformproduct_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('pro_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_pro_name', to='InfoManage.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '预测销量',
                'verbose_name_plural': '预测销量',
                'db_table': 'PredictData',
            },
        ),
        migrations.AlterField(
            model_name='saleform',
            name='deliver_date',
            field=models.DateField(blank=True, null=True, verbose_name='交货时间'),
        ),
    ]
