# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfoManage', '0009_auto_20180519_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictdata',
            options={'verbose_name': '销量预测', 'verbose_name_plural': '销量预测'},
        ),
    ]
